topic_list_tiles:
  type: list
  default: latest|new|unread|top|tags|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile
  description:
    en: "The lists that will be styled with tiles format.  Can be one of latest|new|unread|top|tags|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile"
topic_list_tiles_categories:
  type: list
  list_type: category
  default: ""
  description:
    en: "The categories that will be styled with tiles format."
topic_list_thumbnail:
  type: list
  default: latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile
  description:
    en: "The lists that will include thumbnails.  Can be one of latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile"
topic_list_thumbnails_categories:
  type: list
  list_type: category
  default: ""
  description:
    en: "The categories that will include thumbnails."
topic_list_excerpt:
  type: list
  default: latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile
  description:
    en:  "The lists that will include excerpts.  Can be one of latest|new|unread|top|tags|suggested|agenda|activity-topics|activity-portfolio|latest-mobile|new-mobile|unread-mobile|top-mobile|tags-mobile|agenda-mobile"
topic_list_excerpts_categories:
  type: list
  list_type: category
  default: ""
  description:
    en: "The categories that will include excerpts."
topic_list_tiles_transition_time:
  default: 0.5
  type: float
  description:
    en:  "Number of seconds for tiles layout transition on view change (desktop only)"
topic_list_tiles_larger_featured_tiles:
  default: true
  type: bool
  description:
    en: "Make the tiles with featured tags larger"
topic_list_portfolio:
  default: true
  type: bool
  description:
    en: "Enable additional User Activity view for User Portfolio"
topic_list_portfolio_filter_type:
  default: 'tag'
  type: 'enum'
  description:
    en: "Which type of filter should be used to limit Activity Portfolio Topics"
  choices:
    - tag
    - category
topic_list_portfolio_filter_parameter:
  default: ''
  type: string
  description:
    en:  "Enter the tag or category slug (depending of value of filter type setting)"
topic_list_set_category_defaults:
  default: false
  type: bool
  description:
    en:  "Set site topic list display settings as defaults for category topic lists."
topic_list_default_thumbnail:
  default: ''
  type: string
  description:
    en:  "Image URL for default thumbnail if topic thumbnail is inaccessible."
topic_list_default_thumbnail_fallback:
  default: false
  type: bool
  description:
    en:  "Use the default thumbnail when a topic has no previewed image."
topic_list_thumbnail_resolution_level:
  default: 2
  type: integer
  description:
    en:  "Resolution level of thumbnail used: 0 is original, 1 is up to 800x800 , 2 is up to 400x400, 3 is up to 200x200, 4 is up to 100x100"
topic_list_thumbnail_width:
  default: 150
  description:
    en: "Width of image that can be previewed."
topic_list_thumbnail_height:
  default: 100
  description:
    en: "Height of image that can be previewed."
topic_list_thumbnail_first_x_rows:
  default: 0
  type: integer
  description:
    en: "Show thumbnail only for first X rows. Enter 0 to show on all rows."
topic_list_featured_images:
  default: false
  type: bool
  description:
    en: "Enable featured images for non-category routes."
topic_list_featured_images_category:
  default: false
  type: bool
  description:
    en: "Apply featured images site setting to all category discovery routes"
topic_list_featured_images_tag:
  type: list
  list_type: tag
  default: ''
  description:
    en: "Featured images tag."
topic_list_featured_images_tag_show:
  default: true
  type: bool
  description:
    en: "Show featured images tag below featured images."
topic_list_featured_images_count:
  default: 0
  description:
    en: "Featured Images Topics set count. Set to zero for no limit. NB If featured Topics don't contain a thumbnail the number of images will be fewer, just raise the number."
topic_list_featured_width:
  default: 0
  type: integer
  description:
    en: "Featured image width.  Setting this to zero will make it responsive to image aspect ratio."
topic_list_featured_height:
  default: 150
  type: integer
  description:
    en: "Featured image height."
topic_list_featured_title:
  default: ''
  type: string
  description:
    en: "Featured images title. Supports Markdown."
topic_list_featured_excerpt:
  default: 100
  type: integer
  description:
    en: "Include topic excerpt in featured image and determine its length.  Set it to 0 for don't include"
topic_list_test_image_url_timeout:
  default: 5000
  type: integer
  description:
    en: "Timeout for testing image url"
topic_list_fade_in_time:
  default: 0
  type: integer
  description:
    en: "Optional fade in of Topic Lists in milliseconds.  0 means OFF"
